import fs from 'node:fs';
import path from 'node:path';

const file = path.resolve('src/App.js');
let text = fs.readFileSync(file, 'utf8');
if (text.includes('SOURCE_FILE_URL: ${fileUrl}')) process.exit(0);

const oldState = `  const [timeLeft, setTimeLeft] = useState(90);\n  const [fileName, setFileName] = useState('');\n\n  const handleFileUpload = (e) => {\n    const file = e.target.files[0];\n    if (file) {\n      setFileName(file.name);\n      if (file.type === "text/plain") {\n        const reader = new FileReader();\n        reader.onload = (ev) => {\n          setInput(ev.target.result.substring(0, 5000)); // Limit to 5000 chars for prompt safety\n        };\n        reader.readAsText(file);\n      } else {\n        setInput(\`Create a quiz about \${file.name}\`);\n      }\n    }\n  };`;
const newState = `  const [timeLeft, setTimeLeft] = useState(90);\n  const [fileName, setFileName] = useState('');\n  const [fileUrl, setFileUrl] = useState('');\n  const [fileMimeType, setFileMimeType] = useState('');\n  const [fileUploading, setFileUploading] = useState(false);\n\n  const handleFileUpload = async (e) => {\n    const file = e.target.files?.[0];\n    if (!file) return;\n    const allowed = /\\.(txt|md|csv|pdf|doc|docx|ppt|pptx|xls|xlsx)$/i.test(file.name);\n    if (!allowed) { showToast("Unsupported file. Use PDF, DOC/DOCX, PPT/PPTX, XLS/XLSX, TXT or MD.", "error"); return; }\n    if (file.size > 8 * 1024 * 1024) { showToast("File is too large. Maximum AI Quiz source size is 8 MB.", "error"); return; }\n    if (!CLOUDINARY_CLOUD_NAME || !CLOUDINARY_UPLOAD_PRESET) { showToast("Quiz file upload is not configured. Please contact the site admin.", "error"); return; }\n    setFileName(file.name); setFileMimeType(file.type || 'application/octet-stream'); setFileUploading(true);\n    try {\n      const formData = new FormData();\n      formData.append('file', file);\n      formData.append('upload_preset', CLOUDINARY_UPLOAD_PRESET);\n      const uploadUrl = \`https://api.cloudinary.com/v1_1/\${CLOUDINARY_CLOUD_NAME}/auto/upload\`;\n      const uploadRes = await fetch(uploadUrl, { method: 'POST', body: formData });\n      const uploadData = await uploadRes.json().catch(() => ({}));\n      if (!uploadRes.ok || uploadData.error || !uploadData.secure_url) throw new Error(uploadData.error?.message || 'Cloudinary upload failed');\n      setFileUrl(uploadData.secure_url);\n      if (file.type === 'text/plain' || /\\.(txt|md|csv)$/i.test(file.name)) {\n        const reader = new FileReader();\n        reader.onload = (ev) => setInput(String(ev.target?.result || '').slice(0, 12000));\n        reader.readAsText(file);\n      } else if (!input.trim()) setInput(file.name.replace(/\\.[^.]+$/, ''));\n      showToast("File attached to AI Quiz source engine.", "success");\n    } catch (error) {\n      console.error("AI Quiz file upload error:", error); setFileUrl('');\n      showToast("Could not upload the quiz source file. Please try again.", "error");\n    } finally { setFileUploading(false); }\n  };`;
if (!text.includes(oldState)) throw new Error('Quiz upload block not found');
text = text.replace(oldState, newState, 1);

const oldPrompt = `    const prompt = \`Generate a valid JSON array of \${limit} multiple choice questions based on the following text or topic: "\${input.substring(0, 2000)}". \n    Style: Short, conceptual questions similar to Virtual University (VU) exam pattern.\n    Format: [{"id": 1, "q": "Question text?", "options": ["Option A", "Option B", "Option C", "Option D"], "ans": 0, "explanation": "Short summary explanation."}]. \n    Return ONLY the raw JSON array. No markdown.\`;`;
const newPrompt = `    const sourceRequest = fileUrl\n      ? \`\\nSOURCE_FILE_URL: \${fileUrl}\\nSOURCE_FILE_NAME: \${fileName}\\nSOURCE_FILE_MIME: \${fileMimeType || 'application/octet-stream'}\\nIMPORTANT: The uploaded file is the primary source. Read the actual file, not merely its filename.\\n\`\n      : '';\n\n    const prompt = \`Generate exactly \${limit} multiple choice questions for the student's requested subject/source.\n\nSTRICT SOURCE RULES:\n- If SOURCE_FILE_URL is present, use that uploaded file as the primary and authoritative source.\n- If the uploaded file already contains MCQs, extract those exact MCQs first: preserve exact question wording, exact four option texts, exact option order, and the source-supported correct answer. Do not paraphrase them.\n- If the source is a handout, lecture notes, PPT/slides, DOC/DOCX or other study material without enough ready-made MCQs, create exam-likely MCQs only from facts explicitly present in that source.\n- If a subject/course is supplied, use matching EduNexus files for that exact course too; never substitute an unrelated course.\n- When several related files are available, prioritize questions/concepts repeated across them and questions appearing in quizzes/question banks/past papers.\n- Never use outside knowledge to fill a missing answer. Skip unsupported questions instead.\n- Every question must have exactly 4 options and exactly one correct answer.\n\nSTUDENT TOPIC/TEXT: \${input.substring(0, 12000)}\n\${sourceRequest}\n\nReturn ONLY raw JSON in this exact shape:\n[{"id":1,"q":"...","options":["...","...","...","..."],"ans":0,"explanation":"Short source-grounded explanation","source":"source title"}]\`;`;
if (!text.includes(oldPrompt)) throw new Error('Quiz generation prompt block not found');
text = text.replace(oldPrompt, newPrompt, 1);

const oldButton = `            <button onClick={generateQuiz} disabled={loading || !input.trim()} className="w-full bg-gradient-to-r from-cyan-600 to-indigo-600 text-white font-bold py-4 rounded-xl shadow-lg transition-all flex items-center justify-center gap-2 disabled:opacity-50 hover:shadow-xl">{loading ? <Loader className="animate-spin h-5 w-5" /> : <PlayCircle className="h-5 w-5" />} {loading ? "Generating Quiz..." : "Start AI Quiz"}</button>`;
const newButton = `            <button onClick={generateQuiz} disabled={loading || fileUploading || (!input.trim() && !fileUrl)} className="w-full bg-gradient-to-r from-cyan-600 to-indigo-600 text-white font-bold py-4 rounded-xl shadow-lg transition-all flex items-center justify-center gap-2 disabled:opacity-50 hover:shadow-xl">{loading || fileUploading ? <Loader className="animate-spin h-5 w-5" /> : <PlayCircle className="h-5 w-5" />} {fileUploading ? "Uploading Source..." : loading ? "Generating Quiz..." : "Start AI Quiz"}</button>`;
if (!text.includes(oldButton)) throw new Error('Quiz button block not found');
text = text.replace(oldButton, newButton, 1);

const oldInput = `              <input value={input} onChange={e => setInput(e.target.value)} className={\`flex-1 \${theme.input} rounded-xl p-4 \${theme.text} outline-none\`} placeholder="e.g. 'CS101' or paste text..." />`;
const newInput = `              <input value={input} onChange={e => setInput(e.target.value)} className={\`flex-1 \${theme.input} rounded-xl p-4 \${theme.text} outline-none\`} placeholder="e.g. CS620, subject name, or paste text..." />`;
if (!text.includes(oldInput)) throw new Error('Quiz input block not found');
text = text.replace(oldInput, newInput, 1);

const oldFile = `            <div className={\`border-2 border-dashed \${theme.border} rounded-xl p-4 text-center cursor-pointer relative hover:bg-slate-50 dark:hover:bg-slate-900 transition-colors\`}>\n              <input type="file" onChange={handleFileUpload} className="absolute inset-0 opacity-0 cursor-pointer" accept=".txt,.pdf,.doc,.docx" />\n              <div className="flex flex-col items-center gap-2">\n                <Upload className="text-indigo-500" />\n                <span className={theme.textMuted}>{fileName || "Click to Upload File (Text/PDF)"}</span>\n              </div>\n            </div>`;
const newFile = `            <div className={\`border-2 border-dashed \${theme.border} rounded-xl p-4 text-center cursor-pointer relative hover:bg-slate-50 dark:hover:bg-slate-900 transition-colors\`}>\n              <input type="file" onChange={handleFileUpload} onClick={(e) => { e.target.value = null; }} className="absolute inset-0 opacity-0 cursor-pointer" accept=".txt,.md,.csv,.pdf,.doc,.docx,.ppt,.pptx,.xls,.xlsx" />\n              <div className="flex flex-col items-center gap-2">\n                <Upload className={fileUrl ? "text-green-500" : "text-indigo-500"} />\n                <span className={theme.textMuted}>{fileName || "Upload PDF / PPT / DOCX / XLSX / TXT"}</span>\n                <span className={\`text-xs \${theme.textMuted}\`}>{fileUrl ? "Source attached ✓ — AI will read the actual file" : "File is uploaded to the source pipeline"}</span>\n              </div>\n            </div>`;
if (!text.includes(oldFile)) throw new Error('Quiz file input block not found');
text = text.replace(oldFile, newFile, 1);

fs.writeFileSync(file, text, 'utf8');
console.log('AI Quiz frontend source pipeline patched.');
