// Only known document hosts and our own generated Storage blob may enter
// an Academic Hub iframe. Other external file links stay downloadable/openable.
const STORAGE_HOST = 'cprpndovdfnkvekewstv.supabase.co';
const PDF_HOSTS = new Set([STORAGE_HOST, 'res.cloudinary.com']);

export function trustedPreviewUrl(links, originalUrl, localUrl = '') {
  if (!links || typeof links !== 'object') return '';
  const kind = String(links.kind || '');
  // Blob URLs are generated by our own app (URL.createObjectURL) from bytes we
  // fetched ourselves, so they are same-origin and safe to frame. Direct-URL
  // PDFs use this path too: Chrome's built-in PDF viewer is blocked in
  // sandboxed cross-origin frames, so ResourcePreview serves those PDFs as
  // same-origin blobs instead of their cross-origin storage URLs.
  if ((kind === 'firebase' || kind === 'pdf') && /^blob:https?:\/\//.test(localUrl)) return localUrl;
  if (!originalUrl || typeof originalUrl !== 'string') return '';
  let url;
  try { url = new URL(originalUrl); } catch { return ''; }
  if (url.protocol !== 'https:' || url.username || url.password) return '';
  if (['drive','document','spreadsheet','presentation'].includes(kind)) {
    const wanted = kind === 'drive' ? 'drive.google.com' : 'docs.google.com';
    // The React app synthesizes these links from a validated Drive ID.
    return url.hostname === wanted
      && /^\/(?:file|document|spreadsheets|presentation)\/d\/[A-Za-z0-9_-]+\/preview$/.test(url.pathname)
      ? url.href : '';
  }
  if (kind === 'pdf' && PDF_HOSTS.has(url.hostname)) {
    if (url.hostname === STORAGE_HOST &&
      !url.pathname.startsWith('/storage/v1/object/public/edunexus-public-files/')) return '';
    if (url.hostname === 'res.cloudinary.com' &&
      !/\/(?:image|raw|video|auto)\/upload\//.test(url.pathname)) return '';
    return url.href;
  }
  return '';
}

export function previewSandbox(kind) {
  // Drive needs these capabilities to render Google's cross-origin viewer.
  // The parent site is a distinct origin; top navigation is never allowed.
  if (['drive','document','spreadsheet','presentation'].includes(kind))
    return 'allow-scripts allow-same-origin allow-forms allow-popups allow-popups-to-escape-sandbox';
  // Chrome's built-in PDF viewer is blocked inside ANY sandboxed iframe
  // ("This page has been blocked by Chromium") — verified live with
  // sandbox="allow-scripts allow-same-origin" for both direct and blob: URLs,
  // while the same URLs render with no sandbox attribute. Verified PDF blobs
  // (bytes fetched from an allowlisted host and checked for the %PDF-
  // signature in ResourcePreview) therefore render with the sandbox attribute
  // omitted (see the isVerifiedPdfBlob branch). The sandbox below only ever
  // sees Google's document viewer now. Top navigation, forms and popups stay
  // blocked, and only allowlisted URLs ever reach the frame.
  return 'allow-same-origin allow-scripts allow-downloads';
}

/**
 * Build a Google Docs Viewer embed URL for a PDF source URL.
 * Used as the mobile fallback PDF viewer (Android Chrome cannot render
 * blob: PDFs in iframes). Returns '' for invalid input.
 */
export function gviewEmbedUrl(sourceUrl) {
  if (!sourceUrl || typeof sourceUrl !== 'string') return '';
  if (!/^https:\/\//.test(sourceUrl)) return '';
  return 'https://docs.google.com/gview?embedded=1&url=' + encodeURIComponent(sourceUrl);
}
