import React, { useEffect, useState } from 'react';
import { getApps, initializeApp } from 'firebase/app';
import { getAuth, onAuthStateChanged } from 'firebase/auth';
import { getFirestore, doc, onSnapshot, setDoc, serverTimestamp } from 'firebase/firestore';
import { Settings, Save, Plus, Trash2, Pin, Film, ExternalLink } from 'lucide-react';

const firebaseConfig={apiKey:'AIzaSyCdoWl5a0irdMGftJUYkng-dQLUI1ZImP8',authDomain:'edunexus-live-e0b84.firebaseapp.com',projectId:'edunexus-live-e0b84',storageBucket:'edunexus-live-e0b84.firebasestorage.app',messagingSenderId:'464541062794',appId:'1:464541062794:web:7894ed257d604f202bbf73'};
const app=getApps().find(a=>a.name==='[DEFAULT]')||initializeApp(firebaseConfig); const auth=getAuth(app); const db=getFirestore(app);
const SETTINGS=doc(db,'artifacts/edunexus-live/public/data/meta/floatingHub');
const defaults=[['Study Guides','/study-guides'],['Tutorial Videos','/tutorials'],['Student Resources','/student-resources'],['Live Projects','/live-projects']];
const isAdminPage=()=>new URLSearchParams(location.search).get('page')==='admin'||location.pathname.replace(/\/$/,'')==='/admin';
export default function AdminResourceManager(){const [active,setActive]=useState(isAdminPage);const [user,setUser]=useState(null);const [buttons,setButtons]=useState(defaults.map(([label,href])=>({label,href,enabled:true})));const [pinned,setPinned]=useState(true);const [saved,setSaved]=useState(false);
useEffect(()=>{const sync=()=>setActive(isAdminPage());addEventListener('popstate',sync);addEventListener('edunexus:navigation',sync);return()=>{removeEventListener('popstate',sync);removeEventListener('edunexus:navigation',sync)}},[]);useEffect(()=>onAuthStateChanged(auth,setUser),[]);useEffect(()=>active?onSnapshot(SETTINGS,s=>{const d=s.data()||{};if(Array.isArray(d.buttons)&&d.buttons.length)setButtons(d.buttons.map(x=>({label:String(x.label||'Resource'),href:String(x.href||'/'),enabled:x.enabled!==false})));setPinned(d.dashboardPinned!==false)},()=>{}):undefined,[active]);
if(!active||!user?.emailVerified)return null; const admin=user.email==='veducator4@gmail.com'; if(!admin)return null;
const save=async()=>{await setDoc(SETTINGS,{buttons,dashboardPinned:pinned,updatedAt:serverTimestamp(),updatedBy:user.email},{merge:true});localStorage.setItem('edunexus_dashboard_pinned',pinned?'1':'0');dispatchEvent(new Event('edunexus:resource-config'));setSaved(true);setTimeout(()=>setSaved(false),1800)};
return <section style={{position:'fixed',inset:0,zIndex:1100,overflow:'auto',background:'linear-gradient(135deg,#f8fafc,#eef2ff)',padding:'24px 16px 70px',fontFamily:'Inter,system-ui,sans-serif'}}><div style={{maxWidth:1100,margin:'0 auto'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12,marginBottom:18}}><div><div style={{fontSize:11,fontWeight:900,letterSpacing:2,color:'#4f46e5'}}>EDUNEXUS CONTROL CENTER</div><h1 style={{margin:'5px 0',fontSize:'clamp(28px,5vw,44px)',color:'#0f172a'}}>Resource & Video Manager</h1><p style={{margin:0,color:'#64748b'}}>Manage the floating pages and your tutorial video platform without changing the existing dashboard.</p></div><button onClick={()=>{history.pushState({},'', '/');dispatchEvent(new Event('edunexus:navigation'))}} style={{border:0,borderRadius:12,padding:'10px 14px',fontWeight:800,cursor:'pointer'}}>Back</button></div>
<div style={{display:'grid',gap:18}}><article style={{background:'#fff',border:'1px solid #dbe3f0',borderRadius:22,padding:20,boxShadow:'0 18px 50px rgba(15,23,42,.08)'}}><h2 style={{marginTop:0,color:'#0f172a'}}>Floating pages</h2><p style={{color:'#64748b'}}>These names and links control the animated button. Dashboard can stay pinned as the first destination.</p>{buttons.map((b,i)=><div key={i} style={{display:'grid',gridTemplateColumns:'38px 1fr 1fr 70px 42px',gap:8,marginTop:9,alignItems:'center'}}><b style={{textAlign:'center',padding:9,borderRadius:10,background:'#eef2ff',color:'#4f46e5'}}>{i+1}</b><input value={b.label} onChange={e=>setButtons(v=>v.map((x,j)=>j===i?{...x,label:e.target.value}:x))} style={{padding:10,border:'1px solid #dbe3f0',borderRadius:10}}/><input value={b.href} onChange={e=>setButtons(v=>v.map((x,j)=>j===i?{...x,href:e.target.value}:x))} style={{padding:10,border:'1px solid #dbe3f0',borderRadius:10}}/><label style={{fontSize:12,fontWeight:800}}><input type='checkbox' checked={b.enabled} onChange={e=>setButtons(v=>v.map((x,j)=>j===i?{...x,enabled:e.target.checked}:x))}/> On</label><button title='Delete' onClick={()=>setButtons(v=>v.filter((_,j)=>j!==i))} style={{border:0,borderRadius:10,padding:9,color:'#e11d48',cursor:'pointer'}}><Trash2 size={16}/></button></div>)}<div style={{display:'flex',gap:9,marginTop:14,flexWrap:'wrap'}}><button onClick={()=>setButtons(v=>[...v,{label:'New Resource',href:'/',enabled:true}])} style={{display:'inline-flex',gap:6,alignItems:'center',padding:'10px 13px',borderRadius:11,border:'1px solid #dbe3f0',background:'#fff',fontWeight:800,cursor:'pointer'}}><Plus size={16}/> Add page</button><button onClick={()=>setPinned(v=>!v)} style={{display:'inline-flex',gap:6,alignItems:'center',padding:'10px 13px',borderRadius:11,border:'1px solid #dbe3f0',background:pinned?'#eef2ff':'#fff',color:pinned?'#4f46e5':'#475569',fontWeight:800,cursor:'pointer'}}><Pin size={16}/> {pinned?'Dashboard pinned':'Pin Dashboard'}</button><button onClick={save} style={{display:'inline-flex',gap:6,alignItems:'center',padding:'10px 15px',border:0,borderRadius:11,background:'linear-gradient(135deg,#4f46e5,#7c3aed)',color:'#fff',fontWeight:850,cursor:'pointer'}}><Save size={16}/> {saved?'Saved':'Save changes'}</button></div></article>
<article style={{background:'#fff',border:'1px solid #dbe3f0',borderRadius:22,padding:20,boxShadow:'0 18px 50px rgba(15,23,42,.08)'}}><h2 style={{marginTop:0,color:'#0f172a',display:'flex',gap:8,alignItems:'center'}}><Film size={22}/> Video platform</h2><p style={{color:'#64748b'}}>Admin-created tutorials are managed from the existing Tutorials platform. Open it to publish YouTube links or upload owned video files.</p><button onClick={()=>{history.pushState({},'', '/tutorials');dispatchEvent(new Event('edunexus:navigation'))}} style={{display:'inline-flex',gap:7,alignItems:'center',padding:'11px 15px',border:0,borderRadius:11,background:'#0f172a',color:'#fff',fontWeight:800,cursor:'pointer'}}>Open video platform <ExternalLink size={15}/></button></article></div></div></section>}
