import React, { useEffect, useState } from 'react';
import { ArrowRight, ArrowLeft, ExternalLink, GraduationCap, Sparkles } from 'lucide-react';
import './content-hub.css';

const PAGES = {
  guides: { label:'Study Guides', title:'Practical Study Guides for University Students', intro:'Good study advice should be useful on an ordinary Tuesday, not just sound impressive on a poster. These guides focus on the small decisions students actually make: what to study first, how to revise a difficult chapter, how to prepare for an exam, and how to keep progress steady without burning out.', sections:[['Start with a realistic plan','Before opening a book, decide what needs to be finished and how much time you genuinely have. A short plan with clear tasks is easier to follow than a timetable packed from morning to night.'],['Turn notes into active revision','Reading the same page repeatedly feels productive, but recall is stronger when you close the notes and explain the idea yourself. Write a few questions after each topic, answer them without looking, then check what you missed.'],['Use past papers intelligently','Try a paper without notes, mark uncertain questions, and return to the concepts you missed. Keep a small mistake list so the same weak areas do not keep appearing in every practice session.'],['Keep material organised','Use one place for course notes, handouts, practice questions and summaries. Consistent subject folders make revision much less frustrating when exam week arrives.']] },
  'vu-notes-guide': { label:'Academic Hub Guide', title:'How to Use VU Notes, Handouts and Course Material Effectively', intro:'Course material becomes more useful when every file has a purpose. Instead of collecting dozens of PDFs, build a simple workflow: understand the lecture, make a short summary, practise questions, and revisit weak topics before the exam.', sections:[['Lecture first, notes second','Start with the official course material available to you. Use personal notes and supplementary explanations to clarify difficult sections rather than replacing the primary source completely.'],['Make short topic summaries','For every chapter, keep a one-page summary containing definitions, formulas, important examples and the concepts you often forget.'],['Search by course code','Keep material grouped by course code such as CS101, MTH101, ENG101 or PHY101. Consistent naming makes files much easier to locate later.'],['Check information before relying on it','Student-shared material can contain mistakes or old course information. Compare important details with your current course announcements and official LMS material.']] },
  'past-papers': { label:'Exam Preparation', title:'Past Papers: A Better Way to Practise for Exams', intro:'Past papers are not a shortcut to an answer sheet. Their real value is that they show how you perform when questions are timed, mixed together and presented without a chapter heading telling you what method to use.', sections:[['Attempt before checking answers','Give yourself a quiet timed session. Mark uncertain questions instead of guessing and moving on. When you review the paper, separate knowledge gaps from careless mistakes.'],['Build a mistake notebook','Write the question type, why you missed it and the correct method in a few lines. Revisit this notebook regularly.'],['Watch for repeated concepts','When the same topic appears across several papers, treat it as a signal that the underlying concept deserves extra practice. Learn the idea, not the wording.'],['Practise under realistic conditions','Put your phone away, use the allowed time and attempt the paper in one sitting. This also shows whether you are spending too long on a particular question.']] },
  'exam-preparation': { label:'Exam Week Guide', title:'A Calm, Practical Exam Preparation Routine', intro:'The final week is usually not the time to rebuild an entire semester from zero. A better approach is to identify high-value topics, practise retrieval, fix repeated mistakes and protect enough sleep to think clearly on exam day.', sections:[['Seven days before the exam','List every chapter and label it strong, uncertain or weak. Give most of your time to uncertain and weak topics while using short recall sessions to keep strong topics fresh.'],['Three days before the exam','Shift from learning large amounts of new material to mixed practice. Use short quizzes, past questions and your own summaries.'],['The night before','Prepare your documents, stationery and login details early. Avoid turning the final night into an all-nighter. A rested brain is more useful than another few hours of low-quality reading.'],['During the exam','Read the whole question before starting, watch the clock without obsessing over it, and temporarily leave difficult questions that consume too much time.']] },
  'cgpa-guide': { label:'Academic Planning', title:'Understanding CGPA, GPA and Semester Performance', intro:'A CGPA number is more useful when you understand what is behind it. Tracking marks, credit hours and grade points helps you decide where an improvement can have the biggest effect.', sections:[['Think in credit-weighted terms','A course with more credit hours contributes more to the weighted average. Improving a higher-credit course can therefore have a larger effect.'],['Track each semester separately','Keep a simple record of semester GPA, completed credits and difficult subjects. This makes patterns easier to spot early.'],['Use the calculator as an estimate','EduNexus provides a convenient estimate for planning. Always compare it with your official university grading rules and transcript.'],['Set a target you can act on','Choose a concrete target such as improving two weak subjects, completing weekly practice or raising your average score in a particular course.']] },
  'ai-study-tools': { label:'Responsible AI', title:'Using AI Tools Without Losing the Learning', intro:'AI can make study work faster, but the best results come when it supports your thinking rather than replacing it. Use AI to explain a difficult idea, generate practice questions, compare your answer with a model explanation, or turn a topic into flashcards.', sections:[['Ask for explanations, not just answers','If a topic is confusing, ask for a step-by-step explanation and then solve a similar example yourself.'],['Verify important information','AI systems can make confident mistakes. For formulas, dates, official policies and course requirements, check the result against your current material or official source.'],['Use quizzes as retrieval practice','Attempt AI-generated questions without notes and review the explanations afterwards. Keep questions varied so you practise recognition, recall and application.'],['Protect academic integrity','Do not submit generated text as your own work where university rules prohibit it. Use AI as a tutor or revision assistant and follow the rules for your course.']] },
  resources: { label:'Resource Centre', title:'Student Resources, Tools and Quick Links', intro:'EduNexus brings everyday study tools together so students can spend less time searching and more time learning.', sections:[['Academic Hub','Browse course folders, notes, handouts and shared resources. Search by course code or file name when you already know what you need.'],['AI Quiz and Flashcards','Create practice questions or flashcards from a topic and use them for active recall. Short repeated sessions are easier to maintain than one long revision session.'],['Study Planner','Build a study table around your available hours and current subjects. Adjust it whenever your week changes.'],['Articles and Guides','Read practical study advice, academic explainers and student-focused guides as the resource library grows.']] }
};
const projectLinks=[{name:'EduNexus',url:'https://edunexus-app.vercel.app',note:'Student study hub with academic resources, AI tools, articles, discussion, planning and CGPA tools.'},{name:'Online Academy',url:'https://online-academy-plum.vercel.app',note:'Production online-learning project currently deployed through Vercel.'}];
const friendlyPath={'/study-guides':'guides','/vu-notes-guide':'vu-notes-guide','/past-papers':'past-papers','/exam-preparation':'exam-preparation','/cgpa-guide':'cgpa-guide','/ai-study-tools':'ai-study-tools','/student-resources':'resources','/live-projects':'projects'};
export default function ContentHub(){
 const getRoute=()=>new URLSearchParams(window.location.search).get('page')||friendlyPath[window.location.pathname.replace(/\/$/,'')]||'';
 const [route,setRoute]=useState(getRoute);
 useEffect(()=>{const onPop=()=>setRoute(getRoute());window.addEventListener('popstate',onPop);return()=>window.removeEventListener('popstate',onPop)},[]);
 const go=(key)=>{const path=key==='guides'?'/study-guides':key==='resources'?'/student-resources':key==='projects'?'/live-projects':key?`/?page=${key}`:'/';window.history.pushState({page:key},'',path);setRoute(key);window.scrollTo({top:0,behavior:'smooth'});};
 useEffect(()=>{if(!route)return;const titles={guides:'Study Guides for University Students | EduNexus','vu-notes-guide':'How to Use VU Notes and Handouts | EduNexus','past-papers':'Past Papers Exam Preparation Guide | EduNexus','exam-preparation':'Exam Preparation Guide | EduNexus','cgpa-guide':'CGPA and GPA Planning Guide | EduNexus','ai-study-tools':'Responsible AI Study Tools | EduNexus',resources:'Student Resources and Study Tools | EduNexus',projects:'Live Projects and Web Apps | EduNexus'};document.title=titles[route]||'EduNexus';const m=document.querySelector("meta[name='description']");if(m)m.setAttribute('content','Practical student resources, study guides and tools from EduNexus.');},[route]);
 const content=PAGES[route]; if(!content&&route!=='projects')return null;
 return <div className="edux-content-overlay"><div className="edux-content-bg"/><header className="edux-content-nav"><button onClick={()=>go('')} className="edux-brand"><GraduationCap size={22}/><span>EduNexus</span></button><div className="edux-content-links"><button onClick={()=>go('guides')}>Guides</button><button onClick={()=>go('resources')}>Resources</button><button onClick={()=>go('projects')}>Live Projects</button></div><button onClick={()=>go('')} className="edux-back"><ArrowLeft size={15}/> Back to app</button></header><main className="edux-content-main">{route==='projects'?<><section className="edux-hero"><span className="edux-pill">LIVE PROJECTS</span><h1>Projects built and published online</h1><p>A small showcase of deployed web experiences. Visitors open the live site directly; no repository upload is required for normal use.</p></section><div className="edux-project-grid">{projectLinks.map(p=><a className="edux-project" key={p.name} href={p.url} target="_blank" rel="noopener noreferrer"><div className="edux-project-icon"><ExternalLink size={21}/></div><div><h2>{p.name}</h2><span>Live web project</span></div><ArrowRight className="edux-arrow"/><p>{p.note}</p><strong>Open live project →</strong></a>)}</div></>:<><section className="edux-hero"><span className="edux-pill">{content.label}</span><h1>{content.title}</h1><p>{content.intro}</p></section><div className="edux-section-grid">{content.sections.map(([h,t],i)=><article className="edux-section-card" key={h}><span>{String(i+1).padStart(2,'0')}</span><div><h2>{h}</h2><p>{t}</p></div></article>)}</div><section className="edux-note"><Sparkles size={20}/><div><h2>Keep the routine simple</h2><p>Consistent small sessions, organised material and honest practice usually beat a complicated routine that lasts only a few days.</p></div></section><div className="edux-related"><h2>Continue learning</h2><div>{Object.keys(PAGES).filter(k=>k!==route).slice(0,4).map(k=><button key={k} onClick={()=>go(k)}>{PAGES[k].label}<ArrowRight size={14}/></button>)}</div></div></>}</main></div>;
}
