export const runtime = 'nodejs';
export const maxDuration = 30;

const MAX_PROMPT_LENGTH = 50000;
const MAX_FILE_CANDIDATES = 80;
const MAX_SOURCE_FILES = 6;
const MAX_SOURCE_BYTES = 8000000;
const MAX_TOTAL_SOURCE_BYTES = 24000000;
const WINDOW_MS = 60000;
const MAX_REQUESTS_PER_WINDOW = 20;
const PROJECT_ID = 'edunexus-live-e0b84';
const FILES_PATH = `https://firestore.googleapis.com/v1/projects/${PROJECT_ID}/databases/(default)/documents/artifacts/edunexus-live/public/data/files?pageSize=${MAX_FILE_CANDIDATES}`;
const requestLog = new Map();

function getClientKey(req) { return String(req.headers?.['x-forwarded-for'] || req.headers?.['x-real-ip'] || 'unknown').split(',')[0].trim().slice(0, 100); }
function isRateLimited(key) { const now = Date.now(); const recent = (requestLog.get(key) || []).filter(t => now - t < WINDOW_MS); if (recent.length >= MAX_REQUESTS_PER_WINDOW) { requestLog.set(key, recent); return true; } recent.push(now); requestLog.set(key, recent); return false; }
function fitPrompt(value) { const p = String(value || '').trim(); if (p.length <= MAX_PROMPT_LENGTH) return p; return `${p.slice(0, 39000)}\n\n[Context trimmed safely by EduNexus AI]\n\n${p.slice(-10500)}`; }
function typed(v) { if (!v || typeof v !== 'object') return ''; if ('stringValue' in v) return v.stringValue; if ('integerValue' in v) return Number(v.integerValue); if ('doubleValue' in v) return Number(v.doubleValue); if ('booleanValue' in v) return v.booleanValue; if ('timestampValue' in v) return v.timestampValue; if ('referenceValue' in v) return v.referenceValue; if ('arrayValue' in v) return (v.arrayValue.values || []).map(typed); if ('mapValue' in v) return Object.fromEntries(Object.entries(v.mapValue.fields || {}).map(([k,x]) => [k, typed(x)])); return ''; }
function decodeDoc(d) { const out = {}; for (const [k,v] of Object.entries(d?.fields || {})) out[k] = typed(v); return out; }
function urlOf(x) { return String(x?.url || x?.downloadURL || x?.downloadUrl || x?.fileUrl || x?.href || x?.link || '').trim(); }
function titleOf(x) { return String(x?.title || x?.name || x?.fileName || x?.subject || x?.course || 'Untitled file').trim(); }
function termsOf(p) { return String(p || '').toLowerCase().replace(/[^a-z0-9\s-]/g, ' ').split(/\s+/).filter(x => x.length > 1); }
function scoreFile(file, prompt) { const hay = [file.title,file.name,file.fileName,file.subject,file.course,file.code,file.category,file.description,file.text,file.storagePath].map(v => String(v || '').toLowerCase()).join(' '); const terms = termsOf(prompt); const p = String(prompt || '').toLowerCase(); const course = String(file.course || file.subject || file.code || '').toLowerCase(); let score = 0; for (const term of terms) if (hay.includes(term)) score += term.length >= 4 ? 2 : 1; if (course && p.includes(course)) score += 12; if (file.title && p.includes(String(file.title).toLowerCase())) score += 12; if (/quiz|mcq|question|past paper|handout|lecture|notes|slides|ppt|pdf/.test(hay)) score += 2; return score; }
async function fetchLiveFiles() { try { const r = await fetch(FILES_PATH, { headers: { Accept: 'application/json' } }); if (!r.ok) return []; const data = await r.json(); return (data.documents || []).map(d => { const x = decodeDoc(d); return { id: d.name?.split('/').pop() || '', title: titleOf(x), name: x.name || '', fileName: x.fileName || '', subject: x.subject || '', course: x.course || '', code: x.code || '', category: x.category || '', description: x.description || '', text: x.text || x.content || '', contentType: x.contentType || x.mimeType || '', url: urlOf(x), storagePath: x.storagePath || '' }; }).filter(x => x.title || x.url || x.text); } catch (e) { console.warn('Live files lookup failed', e?.message || e); return []; } }
function isQuiz(p) { return /multiple\s+choice|mcq|quiz|question bank|generate.*questions/i.test(String(p || '')); }
function isFlashcard(p) { return /flashcard|flash cards/i.test(String(p || '')); }
function grounded(p) { return isQuiz(p) || isFlashcard(p); }
function quizInstruction() { return `\nSOURCE-GROUNDED EXAM QUIZ MODE:\n1. Use ONLY the supplied EduNexus uploaded source documents and any user-provided source text.\n2. If a source already contains MCQs/questions with options, PRIORITIZE EXACT EXTRACTION. Preserve the question wording, option wording, option order, and correct answer exactly as supported by the source. Do not paraphrase an existing MCQ.\n3. If the source does not contain enough ready-made MCQs, create additional exam-likely MCQs ONLY from facts/concepts explicitly present in the sources.\n4. Prioritize questions repeated across multiple supplied files, repeated in quizzes/past papers, emphasized in headings/definitions, or clearly exam-focused. Do not claim something is most repeated unless repetition is actually visible in the supplied sources.\n5. If the same question appears more than once, keep one clean copy and preserve the source wording.\n6. Every output question MUST have exactly 4 options and exactly one correct answer.\n7. Never use outside knowledge to fill a missing answer. If an answer is not determinable from the supplied material, skip that question.\n8. Return ONLY valid JSON array: [{"id":1,"q":"...","options":["...","...","...","..."],"ans":0,"explanation":"Short source-grounded explanation","source":"exact source title"}]\n`; }
function flashcardInstruction() { return `\nSOURCE-GROUNDED FLASHCARD MODE:\nUse ONLY the supplied EduNexus sources. Prefer definitions, key concepts, comparisons, formulas, examples and exam-important points explicitly present in the material. Never invent missing facts. Return ONLY JSON array of {"front":"...","back":"...","source":"..."}.\n`; }
function genericInstruction() { return 'EduNexus AI: answer naturally and accurately. When source documents are supplied, use them as authoritative evidence and never invent file names, facts or URLs.'; }
async function downloadSource(file) { if (file.text) return { text: `SOURCE DOCUMENT: ${file.title}\nCourse/Subject: ${file.course || file.subject || file.code || 'N/A'}\nSOURCE TEXT:\n${String(file.text).slice(0, 70000)}`, bytes: 0 }; if (!file.url) return { text: `SOURCE DOCUMENT: ${file.title}\nNo downloadable URL was supplied. Do not invent contents.`, bytes: 0 }; try { const r = await fetch(file.url, { signal: AbortSignal.timeout(7000) }); if (!r.ok) throw new Error(`source ${r.status}`); const buf = await r.arrayBuffer(); if (buf.byteLength > MAX_SOURCE_BYTES) return { text: `SOURCE DOCUMENT: ${file.title}\nThis file exceeds the safe ingestion size. Do not invent contents.`, bytes: 0 }; const ct = String(r.headers.get('content-type') || file.contentType || '').toLowerCase(); const isPdf = ct.includes('pdf') || /\.pdf(?:$|\?)/i.test(file.url); const isText = ct.startsWith('text/') || /json|csv|xml|html|markdown/i.test(ct) || /\.(txt|csv|json|md|html?)(?:$|\?)/i.test(file.url); if (isPdf) return { parts: [{ text: `SOURCE DOCUMENT: ${file.title}\nCourse/Subject: ${file.course || file.subject || file.code || 'N/A'}\n` }, { inlineData: { mimeType: 'application/pdf', data: Buffer.from(buf).toString('base64') } }], bytes: buf.byteLength }; if (isText) return { text: `SOURCE DOCUMENT: ${file.title}\nCourse/Subject: ${file.course || file.subject || file.code || 'N/A'}\nSOURCE TEXT:\n${Buffer.from(buf).toString('utf8').slice(0, 70000)}`, bytes: buf.byteLength }; return { text: `SOURCE DOCUMENT: ${file.title}\nThe uploaded type ${ct || 'unknown'} is not directly extractable here. Prefer PDF for document understanding. Do not invent its contents.`, bytes: 0 }; } catch (_) { return { text: `SOURCE DOCUMENT: ${file.title}\nThe live source could not be downloaded in this request. Do not invent its contents.`, bytes: 0 }; } }
async function buildSources(prompt) { const files = await fetchLiveFiles(); const ranked = files.map(file => ({ file, score: scoreFile(file, prompt) })).sort((a,b) => b.score - a.score); const selected = grounded(prompt) ? ranked.filter(x => x.score > 0).slice(0, MAX_SOURCE_FILES) : ranked.filter(x => x.score > 0).slice(0, 3); if (grounded(prompt) && !selected.length) return { selected: [], parts: [], sourceNames: [] }; const parts = []; const selectedMeta = []; let total = 0; for (const item of selected) { if (total >= MAX_TOTAL_SOURCE_BYTES) break; const got = await downloadSource(item.file); total += got.bytes || 0; if (got.parts) parts.push(...got.parts); else parts.push({ text: got.text }); selectedMeta.push({ title: item.file.title, course: item.file.course || item.file.subject || item.file.code || '', score: item.score }); } return { selected: selectedMeta, parts, sourceNames: selectedMeta.map(x => x.title) }; }

export default async function handler(req, res) {\n  if (req.method !== 'POST') { res.setHeader('Allow','POST'); return res.status(405).json({error:'Method not allowed'}); }\n  if (isRateLimited(getClientKey(req))) return res.status(429).json({error:'Too many requests. Please try again shortly.'});\n  const apiKey = process.env.GEMINI_API_KEY;\n  if (!apiKey) return res.status(503).json({code:'GEMINI_NOT_CONFIGURED', error:'AI service is not configured yet.'});\n  const rawPrompt = req.body?.prompt;\n  if (typeof rawPrompt !== 'string' || !rawPrompt.trim()) return res.status(400).json({error:'A non-empty prompt is required.'});\n  const prompt = fitPrompt(rawPrompt);\n  const isGrounded = grounded(prompt);\n  const sources = await buildSources(prompt);\n  if (isGrounded && !sources.selected.length) return res.status(422).json({error:'No matching uploaded EduNexus handout/file was found for this topic. Upload or select the course material first.'});\n  const instructions = isQuiz(prompt) ? quizInstruction() : isFlashcard(prompt) ? flashcardInstruction() : genericInstruction();\n  const sourceHeader = sources.parts.length ? `\\n\\nLIVE UPLOADED SOURCES (${sources.sourceNames.join(', ')})\\nTreat these sources as authoritative.` : '';\n  const contents = [{ role:'user', parts:[{text:`${instructions}\\n\\n${prompt}${sourceHeader}`}, ...sources.parts] }];\n  const controller = new AbortController(); const timeout = setTimeout(() => controller.abort(), 29000);\n  try {\n    const response = await fetch('https://generativelanguage.googleapis.com/v1/models/gemini-2.5-flash:generateContent', { method:'POST', signal:controller.signal, headers:{'Content-Type':'application/json','x-goog-api-key':apiKey}, body:JSON.stringify({contents,generationConfig:isGrounded ? {temperature:0.15,responseMimeType:'application/json'} : {temperature:0.45}}) });\n    const data = await response.json().catch(() => null);\n    if (!response.ok || data?.error) return res.status(502).json({error:'The AI provider could not complete the request.'});\n    const text = data?.candidates?.[0]?.content?.parts?.map(p => typeof p?.text === 'string' ? p.text : '').filter(Boolean).join('\\n').trim();\n    if (!text) return res.status(502).json({error:'The AI provider returned no text.'});\n    return res.status(200).json({text, sources:sources.selected});\n  } catch (e) { return res.status(e?.name === 'AbortError' ? 504 : 500).json({error:e?.name === 'AbortError' ? 'The AI request timed out.' : 'The AI request failed on the server.'}); }\n  finally { clearTimeout(timeout); }\n}\n